#!/bin/sh

alias vi=vimx
alias vim=vimx

alias python=python3
alias python2=python
alias pip=python3-pip

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

function snetlist {
  gnetlist -g spice-sdb -o "${1%sch}ckt" "$1"
}
